In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [48]:
# Load the original dataset
# NOTE: This notebook runs on Google Colab, so file paths differ from a local PC.
# Mount Google Drive first, then read the file from /content/drive/MyDrive/...
# Update the path below to match where the dataset is saved in your own Drive.
raw_df = pd.read_csv("/content/AmesHousing.csv")
pd.set_option('display.max_columns',None)

# Create a separate working DataFrame
df = raw_df.copy()

# Inspect the data
# display the first 5 rows of data
print(df.head())

   Order        PID  MS SubClass MS Zoning  Lot Frontage  Lot Area Street  \
0      1  526301100           20        RL         141.0     31770   Pave
1      2  526350040           20        RH          80.0     11622   Pave
2      3  526351010           20        RL          81.0     14267   Pave
3      4  526353030           20        RL          93.0     11160   Pave
4      5  527105010           60        RL          74.0     13830   Pave

  Alley Lot Shape Land Contour Utilities Lot Config Land Slope Neighborhood  \
0   NaN       IR1          Lvl    AllPub     Corner        Gtl        NAmes
1   NaN       Reg          Lvl    AllPub     Inside        Gtl        NAmes
2   NaN       IR1          Lvl    AllPub     Corner        Gtl        NAmes
3   NaN       Reg          Lvl    AllPub     Corner        Gtl        NAmes
4   NaN       IR1          Lvl    AllPub     Inside        Gtl      Gilbert

  Condition 1 Condition 2 Bldg Type House Style  Overall Qual  Overall Cond  \
0        Norm        Norm      1Fam      1Story             6             5
1       Feedr        Norm      1Fam      1Story             5             6
2        Norm        Norm      1Fam      1Story             6             6
3        Norm        Norm      1Fam      1Story             7             5
4        Norm        Norm      1Fam      2Story             5             5

   Year Built  Year Remod/Add Roof Style Roof Matl Exterior 1st Exterior 2nd  \
0        1960            1960        Hip   CompShg      BrkFace      Plywood
1        1961            1961      Gable   CompShg      VinylSd      VinylSd
2        1958            1958        Hip   CompShg      Wd Sdng      Wd Sdng
3        1968            1968        Hip   CompShg      BrkFace      BrkFace
4        1997            1998      Gable   CompShg      VinylSd      VinylSd

  Mas Vnr Type  Mas Vnr Area Exter Qual Exter Cond Foundation Bsmt Qual  \
0        Stone         112.0         TA         TA     CBlock        TA
1          NaN           0.0         TA         TA     CBlock        TA
2      BrkFace         108.0         TA         TA     CBlock        TA
3          NaN           0.0         Gd         TA     CBlock        TA
4          NaN           0.0         TA         TA      PConc        Gd

  Bsmt Cond Bsmt Exposure BsmtFin Type 1  BsmtFin SF 1 BsmtFin Type 2  \
0        Gd            Gd            BLQ         639.0            Unf
1        TA            No            Rec         468.0            LwQ
2        TA            No            ALQ         923.0            Unf
3        TA            No            ALQ        1065.0            Unf
4        TA            No            GLQ         791.0            Unf

   BsmtFin SF 2  Bsmt Unf SF  Total Bsmt SF Heating Heating QC Central Air  \
0           0.0        441.0         1080.0    GasA         Fa           Y
1         144.0        270.0          882.0    GasA         TA           Y
2           0.0        406.0         1329.0    GasA         TA           Y
3           0.0       1045.0         2110.0    GasA         Ex           Y
4           0.0        137.0          928.0    GasA         Gd           Y

  Electrical  1st Flr SF  2nd Flr SF  Low Qual Fin SF  Gr Liv Area  \
0      SBrkr        1656           0                0         1656
1      SBrkr         896           0                0          896
2      SBrkr        1329           0                0         1329
3      SBrkr        2110           0                0         2110
4      SBrkr         928         701                0         1629

   Bsmt Full Bath  Bsmt Half Bath  Full Bath  Half Bath  Bedroom AbvGr  \
0             1.0             0.0          1          0              3
1             0.0             0.0          1          0              2
2             0.0             0.0          1          1              3
3             1.0             0.0          2          1              3
4             0.0             0.0          2          1              3

   Kitchen AbvGr Kitchen Qual  TotRms AbvGrd Functional  Fireplaces  \
0              1           TA              7        Typ           2
1              1           TA              5        Typ           0
2              1           Gd              6        Typ           0
3              1           Ex              8        Typ           2
4              1           TA              6        Typ           1

  Fireplace Qu Garage Type  Garage Yr Blt Garage Finish  Garage Cars  \
0           Gd      Attchd         1960.0           Fin          2.0
1          NaN      Attchd         1961.0           Unf          1.0
2          NaN      Attchd         1958.0           Unf          1.0
3           TA      Attchd         1968.0           Fin          2.0
4           TA      Attchd         1997.0           Fin          2.0

   Garage Area Garage Qual Garage Cond Paved Drive  Wood Deck SF  \
0        528.0          TA          TA           P           210
1        730.0          TA          TA           Y           140
2        312.0          TA          TA           Y           393
3        522.0          TA          TA           Y             0
4        482.0          TA          TA           Y           212

   Open Porch SF  Enclosed Porch  3Ssn Porch  Screen Porch  Pool Area Pool QC  \
0             62               0           0             0          0     NaN
1              0               0           0           120          0     NaN
2             36               0           0             0          0     NaN
3              0               0           0             0          0     NaN
4             34               0           0             0          0     NaN

   Fence Misc Feature  Misc Val  Mo Sold  Yr Sold Sale Type Sale Condition  \
0    NaN          NaN         0        5     2010       WD          Normal
1  MnPrv          NaN         0        6     2010       WD          Normal
2    NaN         Gar2     12500        6     2010       WD          Normal
3    NaN          NaN         0        4     2010       WD          Normal
4  MnPrv          NaN         0        3     2010       WD          Normal

   SalePrice
0     215000
1     105000
2     172000
3     244000
4     189900

**Drop unnecessary Columns**

In [49]:
df = df.drop(["Order","PID"],axis=1)
print(df.shape)

(2930, 80)

In [50]:
X = df.drop(['SalePrice'],axis=1)
y = df['SalePrice']

In [51]:
print(X.head())
print(y.head())

   MS SubClass MS Zoning  Lot Frontage  Lot Area Street Alley Lot Shape  \
0           20        RL         141.0     31770   Pave   NaN       IR1
1           20        RH          80.0     11622   Pave   NaN       Reg
2           20        RL          81.0     14267   Pave   NaN       IR1
3           20        RL          93.0     11160   Pave   NaN       Reg
4           60        RL          74.0     13830   Pave   NaN       IR1

  Land Contour Utilities Lot Config Land Slope Neighborhood Condition 1  \
0          Lvl    AllPub     Corner        Gtl        NAmes        Norm
1          Lvl    AllPub     Inside        Gtl        NAmes       Feedr
2          Lvl    AllPub     Corner        Gtl        NAmes        Norm
3          Lvl    AllPub     Corner        Gtl        NAmes        Norm
4          Lvl    AllPub     Inside        Gtl      Gilbert        Norm

  Condition 2 Bldg Type House Style  Overall Qual  Overall Cond  Year Built  \
0        Norm      1Fam      1Story             6             5        1960
1        Norm      1Fam      1Story             5             6        1961
2        Norm      1Fam      1Story             6             6        1958
3        Norm      1Fam      1Story             7             5        1968
4        Norm      1Fam      2Story             5             5        1997

   Year Remod/Add Roof Style Roof Matl Exterior 1st Exterior 2nd Mas Vnr Type  \
0            1960        Hip   CompShg      BrkFace      Plywood        Stone
1            1961      Gable   CompShg      VinylSd      VinylSd          NaN
2            1958        Hip   CompShg      Wd Sdng      Wd Sdng      BrkFace
3            1968        Hip   CompShg      BrkFace      BrkFace          NaN
4            1998      Gable   CompShg      VinylSd      VinylSd          NaN

   Mas Vnr Area Exter Qual Exter Cond Foundation Bsmt Qual Bsmt Cond  \
0         112.0         TA         TA     CBlock        TA        Gd
1           0.0         TA         TA     CBlock        TA        TA
2         108.0         TA         TA     CBlock        TA        TA
3           0.0         Gd         TA     CBlock        TA        TA
4           0.0         TA         TA      PConc        Gd        TA

  Bsmt Exposure BsmtFin Type 1  BsmtFin SF 1 BsmtFin Type 2  BsmtFin SF 2  \
0            Gd            BLQ         639.0            Unf           0.0
1            No            Rec         468.0            LwQ         144.0
2            No            ALQ         923.0            Unf           0.0
3            No            ALQ        1065.0            Unf           0.0
4            No            GLQ         791.0            Unf           0.0

   Bsmt Unf SF  Total Bsmt SF Heating Heating QC Central Air Electrical  \
0        441.0         1080.0    GasA         Fa           Y      SBrkr
1        270.0          882.0    GasA         TA           Y      SBrkr
2        406.0         1329.0    GasA         TA           Y      SBrkr
3       1045.0         2110.0    GasA         Ex           Y      SBrkr
4        137.0          928.0    GasA         Gd           Y      SBrkr

   1st Flr SF  2nd Flr SF  Low Qual Fin SF  Gr Liv Area  Bsmt Full Bath  \
0        1656           0                0         1656             1.0
1         896           0                0          896             0.0
2        1329           0                0         1329             0.0
3        2110           0                0         2110             1.0
4         928         701                0         1629             0.0

   Bsmt Half Bath  Full Bath  Half Bath  Bedroom AbvGr  Kitchen AbvGr  \
0             0.0          1          0              3              1
1             0.0          1          0              2              1
2             0.0          1          1              3              1
3             0.0          2          1              3              1
4             0.0          2          1              3              1

  Kitchen Qual  TotRms AbvGrd Functional  Fireplaces Fireplace Qu Garage Type  \
0           TA              7        Typ           2           Gd      Attchd
1           TA              5        Typ           0          NaN      Attchd
2           Gd              6        Typ           0          NaN      Attchd
3           Ex              8        Typ           2           TA      Attchd
4           TA              6        Typ           1           TA      Attchd

   Garage Yr Blt Garage Finish  Garage Cars  Garage Area Garage Qual  \
0         1960.0           Fin          2.0        528.0          TA
1         1961.0           Unf          1.0        730.0          TA
2         1958.0           Unf          1.0        312.0          TA
3         1968.0           Fin          2.0        522.0          TA
4         1997.0           Fin          2.0        482.0          TA

  Garage Cond Paved Drive  Wood Deck SF  Open Porch SF  Enclosed Porch  \
0          TA           P           210             62               0
1          TA           Y           140              0               0
2          TA           Y           393             36               0
3          TA           Y             0              0               0
4          TA           Y           212             34               0

   3Ssn Porch  Screen Porch  Pool Area Pool QC  Fence Misc Feature  Misc Val  \
0           0             0          0     NaN    NaN          NaN         0
1           0           120          0     NaN  MnPrv          NaN         0
2           0             0          0     NaN    NaN         Gar2     12500
3           0             0          0     NaN    NaN          NaN         0
4           0             0          0     NaN  MnPrv          NaN         0

   Mo Sold  Yr Sold Sale Type Sale Condition
0        5     2010       WD          Normal
1        6     2010       WD          Normal
2        6     2010       WD          Normal
3        4     2010       WD          Normal
4        3     2010       WD          Normal
0    215000
1    105000
2    172000
3    244000
4    189900
Name: SalePrice, dtype: int64

**Split the Data in Train and Test**

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [54]:
print(X_train.shape)
print(y_train.shape)

(2344, 79)
(2344,)

**Handling NaN/Null Value**

1) Categorical Columns

In [55]:
Categoricalf_na = [feature for feature in X_train.columns if X_train[feature].isnull().sum()>1 and X_train[feature].dtypes == 'O' ]

In [56]:
X_train[Categoricalf_na].head()

,Alley,Mas Vnr Type,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin Type 2,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Pool QC,Fence,Misc Feature
381,NaN,BrkFace,Gd,TA,No,Unf,Unf,TA,Attchd,RFn,TA,TA,NaN,MnPrv,NaN
834,NaN,NaN,TA,Gd,Gd,LwQ,ALQ,NaN,Attchd,Fin,TA,TA,NaN,NaN,NaN
1898,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CarPort,Unf,TA,TA,NaN,NaN,NaN
678,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Detchd,Unf,TA,TA,NaN,NaN,NaN
700,NaN,NaN,Fa,Po,No,Unf,Unf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
X_test[Categoricalf_na].head()

,Alley,Mas Vnr Type,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin Type 2,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Pool QC,Fence,Misc Feature
1357,Grvl,NaN,TA,TA,No,Unf,Unf,Gd,Detchd,Unf,TA,TA,NaN,MnPrv,NaN
2367,NaN,BrkFace,TA,TA,No,ALQ,Unf,NaN,Detchd,Unf,TA,TA,NaN,NaN,NaN
2822,NaN,BrkFace,Gd,TA,No,Unf,Unf,Gd,BuiltIn,Fin,TA,TA,NaN,NaN,NaN
2126,NaN,NaN,Gd,TA,No,GLQ,Unf,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1544,NaN,NaN,TA,TA,No,Rec,GLQ,NaN,Detchd,Unf,TA,TA,NaN,MnPrv,NaN

In [57]:
# missing feature with percent of missing values

for feature in Categoricalf_na:
  print(f"Feature:{feature} and missing Value Percent:{np.round(X_train[feature].isnull().mean(),4)}%")

Feature:Alley and missing Value Percent:0.9309%
Feature:Mas Vnr Type and missing Value Percent:0.6084%
Feature:Bsmt Qual and missing Value Percent:0.026%
Feature:Bsmt Cond and missing Value Percent:0.026%
Feature:Bsmt Exposure and missing Value Percent:0.0269%
Feature:BsmtFin Type 1 and missing Value Percent:0.026%
Feature:BsmtFin Type 2 and missing Value Percent:0.0265%
Feature:Fireplace Qu and missing Value Percent:0.4881%
Feature:Garage Type and missing Value Percent:0.0512%
Feature:Garage Finish and missing Value Percent:0.052%
Feature:Garage Qual and missing Value Percent:0.052%
Feature:Garage Cond and missing Value Percent:0.052%
Feature:Pool QC and missing Value Percent:0.9949%
Feature:Fence and missing Value Percent:0.7995%
Feature:Misc Feature and missing Value Percent:0.9599%

In [ ]:
Categoricalf_na = [feature for feature in X_train.columns if X_train[feature].isnull().sum()>1 and X_train[feature].dtypes == 'O' ]

In [70]:
for feature in Categoricalf_na:
  print(f"Feature:{feature} and missing Value Percent:{np.round(X_test[feature].isnull().mean(),4)}%")

Feature:Alley and missing Value Percent:0.9386%
Feature:Mas Vnr Type and missing Value Percent:0.5956%
Feature:Bsmt Qual and missing Value Percent:0.0324%
Feature:Bsmt Cond and missing Value Percent:0.0324%
Feature:Bsmt Exposure and missing Value Percent:0.0341%
Feature:BsmtFin Type 1 and missing Value Percent:0.0324%
Feature:BsmtFin Type 2 and missing Value Percent:0.0324%
Feature:Fireplace Qu and missing Value Percent:0.4744%
Feature:Garage Type and missing Value Percent:0.0631%
Feature:Garage Finish and missing Value Percent:0.0631%
Feature:Garage Qual and missing Value Percent:0.0631%
Feature:Garage Cond and missing Value Percent:0.0631%
Feature:Pool QC and missing Value Percent:0.9983%
Feature:Fence and missing Value Percent:0.8259%
Feature:Misc Feature and missing Value Percent:0.9795%

**Creating new label as Missing For NaN/Null values**

In [58]:
def replace_cat_feature(X_train,Categoricalf_na):
  data = X_train.copy()

  data[Categoricalf_na] = data[Categoricalf_na].fillna("Missing")
  return data



X_train = replace_cat_feature(X_train,Categoricalf_na)

# check categorical feature have Null value or not

X_train[Categoricalf_na].isnull().sum()

Alley             0
Mas Vnr Type      0
Bsmt Qual         0
Bsmt Cond         0
Bsmt Exposure     0
BsmtFin Type 1    0
BsmtFin Type 2    0
Fireplace Qu      0
Garage Type       0
Garage Finish     0
Garage Qual       0
Garage Cond       0
Pool QC           0
Fence             0
Misc Feature      0
dtype: int64

In [59]:
X_train.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition
381,20,RL,80.0,10400,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,7,5,1976,1976,Gable,CompShg,HdBoard,HdBoard,BrkFace,189.0,TA,TA,CBlock,Gd,TA,No,Unf,0.0,Unf,0.0,1090.0,1090.0,GasA,TA,Y,SBrkr,1370,0,0,1370,0.0,0.0,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2.0,479.0,TA,TA,Y,0,0,0,0,0,0,Missing,MnPrv,Missing,0,6,2009,WD,Family
834,60,RL,NaN,28698,Pave,Missing,IR2,Low,AllPub,CulDSac,Sev,ClearCr,Norm,Norm,1Fam,2Story,5,5,1967,1967,Flat,Tar&Grv,Plywood,Plywood,Missing,0.0,TA,TA,PConc,TA,Gd,Gd,LwQ,249.0,ALQ,764.0,0.0,1013.0,GasA,TA,Y,SBrkr,1160,966,0,2126,0.0,1.0,2,1,3,1,TA,7,Min2,0,Missing,Attchd,1967.0,Fin,2.0,538.0,TA,TA,Y,486,0,0,0,225,0,Missing,Missing,Missing,0,6,2009,WD,Abnorml
1898,90,RL,70.0,9842,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,1962,1962,Gable,CompShg,HdBoard,HdBoard,Missing,0.0,TA,TA,Slab,Missing,Missing,Missing,Missing,0.0,Missing,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1224,0,0,1224,0.0,0.0,2,0,2,2,TA,6,Typ,0,Missing,CarPort,1962.0,Unf,2.0,462.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,3,2007,WD,Normal
678,90,RL,60.0,7200,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,1949,1950,Gable,CompShg,BrkFace,Stone,Missing,0.0,TA,TA,Slab,Missing,Missing,Missing,Missing,0.0,Missing,0.0,0.0,0.0,Wall,Fa,N,FuseF,1040,0,0,1040,0.0,0.0,2,0,2,2,TA,6,Typ,0,Missing,Detchd,1956.0,Unf,2.0,420.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,6,2009,WD,Normal
700,190,RM,63.0,7627,Pave,Missing,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Artery,Norm,2fmCon,2Story,4,6,1920,1950,Gable,CompShg,AsbShng,AsbShng,Missing,0.0,Fa,TA,BrkTil,Fa,Po,No,Unf,0.0,Unf,0.0,600.0,600.0,GasA,Gd,N,SBrkr,1101,600,0,1701,0.0,0.0,2,0,4,2,Fa,8,Typ,0,Missing,Missing,NaN,Missing,0.0,0.0,Missing,Missing,N,0,0,148,0,0,0,Missing,Missing,Missing,0,10,2009,WD,Normal

In [71]:
def replace_cat_feature(X_test,Categoricalf_na):
  data = X_test.copy()

  data[Categoricalf_na] = data[Categoricalf_na].fillna("Missing")
  return data



X_test = replace_cat_feature(X_test,Categoricalf_na)

# check categorical feature have Null value or not

X_test[Categoricalf_na].isnull().sum()

Alley             0
Mas Vnr Type      0
Bsmt Qual         0
Bsmt Cond         0
Bsmt Exposure     0
BsmtFin Type 1    0
BsmtFin Type 2    0
Fireplace Qu      0
Garage Type       0
Garage Finish     0
Garage Qual       0
Garage Cond       0
Pool QC           0
Fence             0
Misc Feature      0
dtype: int64

In [72]:
X_test.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition
1357,70,RM,NaN,5100,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,1Fam,2Story,8,7,1925,1996,Hip,CompShg,Stucco,Wd Shng,Missing,0.0,TA,Gd,PConc,TA,TA,No,Unf,0.0,Unf,0.0,588.0,588.0,GasA,Fa,Y,SBrkr,833,833,0,1666,0.0,0.0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1925.0,Unf,1.0,228.0,TA,TA,Y,192,63,0,0,0,0,Missing,MnPrv,Missing,0,6,2008,WD,Normal
2367,160,RM,21.0,1890,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,6,7,1972,1972,Gable,CompShg,HdBoard,HdBoard,BrkFace,380.0,TA,TA,CBlock,TA,TA,No,ALQ,282.0,Unf,0.0,212.0,494.0,GasA,Ex,Y,SBrkr,494,536,0,1030,0.0,0.0,1,1,3,1,TA,6,Typ,0,Missing,Detchd,1973.0,Unf,1.0,264.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,7,2006,WD,Normal
2822,60,RL,62.0,7162,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,2Story,7,5,2003,2004,Hip,CompShg,HdBoard,Stucco,BrkFace,190.0,Gd,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,796.0,796.0,GasA,Ex,Y,SBrkr,806,918,0,1724,0.0,0.0,2,1,3,1,Gd,8,Typ,1,Gd,BuiltIn,2003.0,Fin,2.0,616.0,TA,TA,Y,168,57,0,0,0,0,Missing,Missing,Missing,0,5,2006,WD,Normal
2126,20,RL,60.0,8070,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,4,5,1994,1995,Gable,CompShg,VinylSd,VinylSd,Missing,0.0,TA,TA,PConc,Gd,TA,No,GLQ,588.0,Unf,0.0,402.0,990.0,GasA,Ex,Y,SBrkr,990,0,0,990,1.0,0.0,1,0,3,1,TA,5,Typ,0,Missing,Missing,NaN,Missing,0.0,0.0,Missing,Missing,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,8,2007,WD,Normal
1544,30,RM,50.0,7000,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,6,8,1926,1998,Gable,CompShg,VinylSd,VinylSd,Missing,0.0,TA,Gd,BrkTil,TA,TA,No,Rec,299.0,GLQ,40.0,555.0,894.0,GasA,TA,Y,SBrkr,919,0,0,919,1.0,0.0,1,0,2,1,TA,5,Typ,0,Missing,Detchd,1926.0,Unf,1.0,195.0,TA,TA,P,0,0,116,0,0,0,Missing,MnPrv,Missing,0,7,2008,WD,Normal

**Numerical Features that Contains NaN/Null Values**

In [60]:
numericalf_na = [feature for feature in X_train.columns if X_train[feature].isnull().sum()>1 and X_train[feature].dtypes !='O']

In [61]:
X_train[numericalf_na].head()

      Lot Frontage  Mas Vnr Area  Garage Yr Blt
381           80.0         189.0         1976.0
834            NaN           0.0         1967.0
1898          70.0           0.0         1962.0
678           60.0           0.0         1956.0
700           63.0           0.0            NaN

In [62]:
# finding each feature with missing value percent

for feature in numericalf_na:
  print(f"Feature:{feature} and Missing Value in Percent:{np.round(X_train[feature].isnull().mean(),4)}%")

Feature:Lot Frontage and Missing Value in Percent:0.1677%
Feature:Mas Vnr Area and Missing Value in Percent:0.0081%
Feature:Garage Yr Blt and Missing Value in Percent:0.052%

In [63]:
# Replacing Numerical NaN values as median with creating new feature featue+'nan'

for feature in numericalf_na:
  median_value = X_train[feature].median()

  X_train[feature+'NaN'] = np.where(X_train[feature].isnull(),1,0)
  X_train[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table


X_train[numericalf_na].isnull().sum()

/tmp/ipykernel_508/3693465190.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table
/tmp/ipykernel_508/3693465190.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table
/tmp/ipykernel_508/3693465190.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_train[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table

Lot Frontage     0
Mas Vnr Area     0
Garage Yr Blt    0
dtype: int64

In [65]:
X_train.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Yr Blt,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,Lot FrontageNaN,Mas Vnr AreaNaN,Garage Yr BltNaN
381,20,RL,80.0,10400,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,7,5,1976,1976,Gable,CompShg,HdBoard,HdBoard,BrkFace,189.0,TA,TA,CBlock,Gd,TA,No,Unf,0.0,Unf,0.0,1090.0,1090.0,GasA,TA,Y,SBrkr,1370,0,0,1370,0.0,0.0,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2.0,479.0,TA,TA,Y,0,0,0,0,0,0,Missing,MnPrv,Missing,0,6,2009,WD,Family,0,0,0
834,60,RL,68.0,28698,Pave,Missing,IR2,Low,AllPub,CulDSac,Sev,ClearCr,Norm,Norm,1Fam,2Story,5,5,1967,1967,Flat,Tar&Grv,Plywood,Plywood,Missing,0.0,TA,TA,PConc,TA,Gd,Gd,LwQ,249.0,ALQ,764.0,0.0,1013.0,GasA,TA,Y,SBrkr,1160,966,0,2126,0.0,1.0,2,1,3,1,TA,7,Min2,0,Missing,Attchd,1967.0,Fin,2.0,538.0,TA,TA,Y,486,0,0,0,225,0,Missing,Missing,Missing,0,6,2009,WD,Abnorml,1,0,0
1898,90,RL,70.0,9842,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,1962,1962,Gable,CompShg,HdBoard,HdBoard,Missing,0.0,TA,TA,Slab,Missing,Missing,Missing,Missing,0.0,Missing,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1224,0,0,1224,0.0,0.0,2,0,2,2,TA,6,Typ,0,Missing,CarPort,1962.0,Unf,2.0,462.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,3,2007,WD,Normal,0,0,0
678,90,RL,60.0,7200,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,1949,1950,Gable,CompShg,BrkFace,Stone,Missing,0.0,TA,TA,Slab,Missing,Missing,Missing,Missing,0.0,Missing,0.0,0.0,0.0,Wall,Fa,N,FuseF,1040,0,0,1040,0.0,0.0,2,0,2,2,TA,6,Typ,0,Missing,Detchd,1956.0,Unf,2.0,420.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,6,2009,WD,Normal,0,0,0
700,190,RM,63.0,7627,Pave,Missing,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Artery,Norm,2fmCon,2Story,4,6,1920,1950,Gable,CompShg,AsbShng,AsbShng,Missing,0.0,Fa,TA,BrkTil,Fa,Po,No,Unf,0.0,Unf,0.0,600.0,600.0,GasA,Gd,N,SBrkr,1101,600,0,1701,0.0,0.0,2,0,4,2,Fa,8,Typ,0,Missing,Missing,1978.0,Missing,0.0,0.0,Missing,Missing,N,0,0,148,0,0,0,Missing,Missing,Missing,0,10,2009,WD,Normal,0,0,1

In [73]:
for feature in numericalf_na:
  print(f"Feature:{feature} and Missing Value in Percent:{np.round(X_test[feature].isnull().mean(),4)}%")

Feature:Lot Frontage and Missing Value in Percent:0.1655%
Feature:Mas Vnr Area and Missing Value in Percent:0.0068%
Feature:Garage Yr Blt and Missing Value in Percent:0.0631%

In [74]:
# Replacing Numerical NaN values as median with creating new feature featue+'nan'

for feature in numericalf_na:
  median_value = X_test[feature].median()

  X_test[feature+'NaN'] = np.where(X_test[feature].isnull(),1,0)
  X_test[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table


X_test[numericalf_na].isnull().sum()

/tmp/ipykernel_508/2374706135.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table
/tmp/ipykernel_508/2374706135.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table
/tmp/ipykernel_508/2374706135.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X_test[feature].fillna(median_value,inplace=True) # inplace = True that means change to the Original Table

Lot Frontage     0
Mas Vnr Area     0
Garage Yr Blt    0
dtype: int64

In [66]:
for feature in ['Year Built', 'Year Remod/Add', 'Garage Yr Blt']:
    X_train[feature] = X_train['Yr Sold'] - X_train[feature]

In [67]:
X_train = X_train.rename(columns={
    'Year Built':     'House Age',
    'Year Remod/Add': 'Years Since Remodel',
    'Garage Yr Blt':  'Garage Age',
})

In [75]:
for feature in ['Year Built', 'Year Remod/Add', 'Garage Yr Blt']:
    X_test[feature] = X_test['Yr Sold'] - X_test[feature]

X_test = X_test.rename(columns={
    'Year Built':     'House Age',
    'Year Remod/Add': 'Years Since Remodel',
    'Garage Yr Blt':  'Garage Age',
})

In [68]:
X_train.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,House Age,Years Since Remodel,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Age,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,Lot FrontageNaN,Mas Vnr AreaNaN,Garage Yr BltNaN
381,20,RL,80.0,10400,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,7,5,33,33,Gable,CompShg,HdBoard,HdBoard,BrkFace,189.0,TA,TA,CBlock,Gd,TA,No,Unf,0.0,Unf,0.0,1090.0,1090.0,GasA,TA,Y,SBrkr,1370,0,0,1370,0.0,0.0,2,0,3,1,TA,6,Typ,1,TA,Attchd,33.0,RFn,2.0,479.0,TA,TA,Y,0,0,0,0,0,0,Missing,MnPrv,Missing,0,6,2009,WD,Family,0,0,0
834,60,RL,68.0,28698,Pave,Missing,IR2,Low,AllPub,CulDSac,Sev,ClearCr,Norm,Norm,1Fam,2Story,5,5,42,42,Flat,Tar&Grv,Plywood,Plywood,Missing,0.0,TA,TA,PConc,TA,Gd,Gd,LwQ,249.0,ALQ,764.0,0.0,1013.0,GasA,TA,Y,SBrkr,1160,966,0,2126,0.0,1.0,2,1,3,1,TA,7,Min2,0,Missing,Attchd,42.0,Fin,2.0,538.0,TA,TA,Y,486,0,0,0,225,0,Missing,Missing,Missing,0,6,2009,WD,Abnorml,1,0,0
1898,90,RL,70.0,9842,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,45,45,Gable,CompShg,HdBoard,HdBoard,Missing,0.0,TA,TA,Slab,Missing,Missing,Missing,Missing,0.0,Missing,0.0,0.0,0.0,GasA,TA,Y,SBrkr,1224,0,0,1224,0.0,0.0,2,0,2,2,TA,6,Typ,0,Missing,CarPort,45.0,Unf,2.0,462.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,3,2007,WD,Normal,0,0,0
678,90,RL,60.0,7200,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,Duplex,1Story,4,5,60,59,Gable,CompShg,BrkFace,Stone,Missing,0.0,TA,TA,Slab,Missing,Missing,Missing,Missing,0.0,Missing,0.0,0.0,0.0,Wall,Fa,N,FuseF,1040,0,0,1040,0.0,0.0,2,0,2,2,TA,6,Typ,0,Missing,Detchd,53.0,Unf,2.0,420.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,6,2009,WD,Normal,0,0,0
700,190,RM,63.0,7627,Pave,Missing,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Artery,Norm,2fmCon,2Story,4,6,89,59,Gable,CompShg,AsbShng,AsbShng,Missing,0.0,Fa,TA,BrkTil,Fa,Po,No,Unf,0.0,Unf,0.0,600.0,600.0,GasA,Gd,N,SBrkr,1101,600,0,1701,0.0,0.0,2,0,4,2,Fa,8,Typ,0,Missing,Missing,31.0,Missing,0.0,0.0,Missing,Missing,N,0,0,148,0,0,0,Missing,Missing,Missing,0,10,2009,WD,Normal,0,0,1

In [76]:
X_test.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Overall Qual,Overall Cond,House Age,Years Since Remodel,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Mas Vnr Area,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin SF 1,BsmtFin Type 2,BsmtFin SF 2,Bsmt Unf SF,Total Bsmt SF,Heating,Heating QC,Central Air,Electrical,1st Flr SF,2nd Flr SF,Low Qual Fin SF,Gr Liv Area,Bsmt Full Bath,Bsmt Half Bath,Full Bath,Half Bath,Bedroom AbvGr,Kitchen AbvGr,Kitchen Qual,TotRms AbvGrd,Functional,Fireplaces,Fireplace Qu,Garage Type,Garage Age,Garage Finish,Garage Cars,Garage Area,Garage Qual,Garage Cond,Paved Drive,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,Lot FrontageNaN,Mas Vnr AreaNaN,Garage Yr BltNaN
1357,70,RM,69.0,5100,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,1Fam,2Story,8,7,83,12,Hip,CompShg,Stucco,Wd Shng,Missing,0.0,TA,Gd,PConc,TA,TA,No,Unf,0.0,Unf,0.0,588.0,588.0,GasA,Fa,Y,SBrkr,833,833,0,1666,0.0,0.0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,83.0,Unf,1.0,228.0,TA,TA,Y,192,63,0,0,0,0,Missing,MnPrv,Missing,0,6,2008,WD,Normal,1,0,0
2367,160,RM,21.0,1890,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,6,7,34,34,Gable,CompShg,HdBoard,HdBoard,BrkFace,380.0,TA,TA,CBlock,TA,TA,No,ALQ,282.0,Unf,0.0,212.0,494.0,GasA,Ex,Y,SBrkr,494,536,0,1030,0.0,0.0,1,1,3,1,TA,6,Typ,0,Missing,Detchd,33.0,Unf,1.0,264.0,TA,TA,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,7,2006,WD,Normal,0,0,0
2822,60,RL,62.0,7162,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,2Story,7,5,3,2,Hip,CompShg,HdBoard,Stucco,BrkFace,190.0,Gd,TA,PConc,Gd,TA,No,Unf,0.0,Unf,0.0,796.0,796.0,GasA,Ex,Y,SBrkr,806,918,0,1724,0.0,0.0,2,1,3,1,Gd,8,Typ,1,Gd,BuiltIn,3.0,Fin,2.0,616.0,TA,TA,Y,168,57,0,0,0,0,Missing,Missing,Missing,0,5,2006,WD,Normal,0,0,0
2126,20,RL,60.0,8070,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,4,5,13,12,Gable,CompShg,VinylSd,VinylSd,Missing,0.0,TA,TA,PConc,Gd,TA,No,GLQ,588.0,Unf,0.0,402.0,990.0,GasA,Ex,Y,SBrkr,990,0,0,990,1.0,0.0,1,0,3,1,TA,5,Typ,0,Missing,Missing,18.0,Missing,0.0,0.0,Missing,Missing,Y,0,0,0,0,0,0,Missing,Missing,Missing,0,8,2007,WD,Normal,0,0,1
1544,30,RM,50.0,7000,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,6,8,82,10,Gable,CompShg,VinylSd,VinylSd,Missing,0.0,TA,Gd,BrkTil,TA,TA,No,Rec,299.0,GLQ,40.0,555.0,894.0,GasA,TA,Y,SBrkr,919,0,0,919,1.0,0.0,1,0,2,1,TA,5,Typ,0,Missing,Detchd,82.0,Unf,1.0,195.0,TA,TA,P,0,0,116,0,0,0,Missing,MnPrv,Missing,0,7,2008,WD,Normal,0,0,0

In [77]:
# we notice in Histogram feature vs SalePrice
# that Some of Numerical Features are Skewed

# here we convert into normal distribution using log Distribution

skewed_numf = ['Lot Frontage','Lot Area','1st Flr SF','Gr Liv Area']

for feature in skewed_numf:
  X_train[feature] = np.log(X_train[feature])


for feature in skewed_numf:
  X_test[feature] = np.log(X_test[feature])

In [96]:
y_train_log = np.log(y_train)
y_train_log.head()

y_test_log = np.log(y_test)
y_test_log.head()

1357    2.484003
2367    2.456280
2822    2.500486
2126    2.461707
1544    2.463346
Name: SalePrice, dtype: float64

In [84]:
# Rare Categorical Feature means Category having less than 1 percent

categorical_f = [feature for feature in X_train.columns if X_train[feature].dtypes=='O']

In [86]:
rare_labels = {}   # must be created before the loop

for feature in categorical_f:
    freq = X_train[feature].value_counts(normalize=True)   # share of each category
    rare_labels[feature] = freq[freq < 0.01].index.tolist()  # categories under 1%

In [87]:
for feature in categorical_f:
    X_train[feature] = X_train[feature].where(~X_train[feature].isin(rare_labels[feature]), 'Rare')
    X_test[feature]  = X_test[feature].where(~X_test[feature].isin(rare_labels[feature]), 'Rare')

In [88]:
X_train[categorical_f].head()

,MS Zoning,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin Type 2,Heating,Heating QC,Central Air,Electrical,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Pool QC,Fence,Misc Feature,Sale Type,Sale Condition
381,RL,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,Gable,CompShg,HdBoard,HdBoard,BrkFace,TA,TA,CBlock,Gd,TA,No,Unf,Unf,GasA,TA,Y,SBrkr,TA,Typ,TA,Attchd,RFn,TA,TA,Y,Missing,MnPrv,Missing,WD,Family
834,RL,Pave,Missing,IR2,Low,AllPub,CulDSac,Rare,ClearCr,Norm,Norm,1Fam,2Story,Rare,Rare,Plywood,Plywood,Missing,TA,TA,PConc,TA,Gd,Gd,LwQ,ALQ,GasA,TA,Y,SBrkr,TA,Min2,Missing,Attchd,Fin,TA,TA,Y,Missing,Missing,Missing,WD,Abnorml
1898,RL,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,NAmes,Norm,Norm,Duplex,1Story,Gable,CompShg,HdBoard,HdBoard,Missing,TA,TA,Slab,Missing,Missing,Missing,Missing,Missing,GasA,TA,Y,SBrkr,TA,Typ,Missing,Rare,Unf,TA,TA,Y,Missing,Missing,Missing,WD,Normal
678,RL,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,Duplex,1Story,Gable,CompShg,BrkFace,Rare,Missing,TA,TA,Slab,Missing,Missing,Missing,Missing,Missing,Rare,Fa,N,FuseF,TA,Typ,Missing,Detchd,Unf,TA,TA,Y,Missing,Missing,Missing,WD,Normal
700,RM,Pave,Missing,Reg,Lvl,AllPub,Corner,Gtl,OldTown,Artery,Norm,2fmCon,2Story,Gable,CompShg,AsbShng,AsbShng,Missing,Fa,TA,BrkTil,Fa,Rare,No,Unf,Unf,GasA,Gd,N,SBrkr,Fa,Typ,Missing,Missing,Missing,Missing,Missing,N,Missing,Missing,Missing,WD,Normal

In [91]:
X_test[categorical_f].head(10)

,MS Zoning,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,Land Slope,Neighborhood,Condition 1,Condition 2,Bldg Type,House Style,Roof Style,Roof Matl,Exterior 1st,Exterior 2nd,Mas Vnr Type,Exter Qual,Exter Cond,Foundation,Bsmt Qual,Bsmt Cond,Bsmt Exposure,BsmtFin Type 1,BsmtFin Type 2,Heating,Heating QC,Central Air,Electrical,Kitchen Qual,Functional,Fireplace Qu,Garage Type,Garage Finish,Garage Qual,Garage Cond,Paved Drive,Pool QC,Fence,Misc Feature,Sale Type,Sale Condition
1357,RM,Pave,Grvl,Reg,Lvl,AllPub,Inside,Gtl,OldTown,Norm,Norm,1Fam,2Story,Hip,CompShg,Stucco,Wd Shng,Missing,TA,Gd,PConc,TA,TA,No,Unf,Unf,GasA,Fa,Y,SBrkr,Gd,Typ,Gd,Detchd,Unf,TA,TA,Y,Missing,MnPrv,Missing,WD,Normal
2367,RM,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,BrDale,Norm,Norm,Twnhs,2Story,Gable,CompShg,HdBoard,HdBoard,BrkFace,TA,TA,CBlock,TA,TA,No,ALQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Missing,Detchd,Unf,TA,TA,Y,Missing,Missing,Missing,WD,Normal
2822,RL,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,2Story,Hip,CompShg,HdBoard,Stucco,BrkFace,Gd,TA,PConc,Gd,TA,No,Unf,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Gd,BuiltIn,Fin,TA,TA,Y,Missing,Missing,Missing,WD,Normal
2126,RL,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,Missing,TA,TA,PConc,Gd,TA,No,GLQ,Unf,GasA,Ex,Y,SBrkr,TA,Typ,Missing,Missing,Missing,Missing,Missing,Y,Missing,Missing,Missing,WD,Normal
1544,RM,Pave,Missing,Reg,Lvl,AllPub,Inside,Gtl,IDOTRR,Norm,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,Missing,TA,Gd,BrkTil,TA,TA,No,Rec,GLQ,GasA,TA,Y,SBrkr,TA,Typ,Missing,Detchd,Unf,TA,TA,P,Missing,MnPrv,Missing,WD,Normal
2415,RL,Pave,Missing,IR1,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,1Story,Gable,CompShg,VinylSd,VinylSd,Missing,Gd,TA,PConc,Gd,TA,Av,Unf,Unf,GasA,Ex,Y,SBrkr,Gd,Typ,Missing,Attchd,Fin,TA,TA,Y,Missing,Missing,Missing,New,Partial
2227,RM,Pave,Missing,IR1,Bnk,AllPub,Inside,Mod,Rare,Norm,Norm,TwnhsE,1Story,Gable,CompShg,HdBoard,HdBoard,Missing,TA,TA,CBlock,Gd,TA,Gd,GLQ,Unf,GasA,Gd,Y,SBrkr,TA,Typ,Missing,Attchd,Unf,TA,TA,Y,Missing,Missing,Missing,WD,Normal
410,RL,Pave,Missing,Reg,Lvl,AllPub,FR2,Gtl,Rare,Norm,Norm,Twnhs,2Story,Gable,CompShg,Plywood,Rare,Missing,TA,TA,CBlock,Gd,TA,No,ALQ,Unf,GasA,TA,Y,SBrkr,TA,Typ,TA,Attchd,Unf,TA,TA,Y,Missing,Missing,Missing,WD,Normal
761,RL,Pave,Missing,IR1,Lvl,AllPub,Inside,Gtl,Sawyer,Norm,Norm,1Fam,1Story,Gable,CompShg,MetalSd,MetalSd,Missing,TA,Gd,CBlock,Fa,TA,No,Unf,Unf,GasA,Ex,Y,FuseA,Fa,Typ,Missing,Rare,Unf,TA,TA,Y,Missing,Missing,Missing,WD,Normal
436,RL,Pave,Missing,Rare,Lvl,AllPub,CulDSac,Gtl,NridgHt,Norm,Norm,1Fam,2Story,Gable,CompShg,VinylSd,VinylSd,Stone,Gd,TA,PConc,Ex,TA,Av,GLQ,Unf,GasA,Ex,Y,SBrkr,Ex,Typ,Gd,BuiltIn,Fin,TA,TA,Y,Missing,Missing,Missing,WD,Family

In [92]:
for feature in categorical_f:
    # 1. Average price per category, using train only.
    #    y_train has the prices; X_train[feature] tells which category each row is in.
    #    Sorted from cheapest category to most expensive.
    means = y_train.groupby(X_train[feature]).mean().sort_values()

    # 2. Give each category a number: cheapest = 0, next = 1, next = 2, ...
    labels_ordered = {k: i for i, k in enumerate(means.index, 0)}

    # 3. Replace the text with its number in BOTH train and test,
    #    using the same mapping learned from train.
    X_train[feature] = X_train[feature].map(labels_ordered)
    X_test[feature]  = X_test[feature].map(labels_ordered)

# 4. Categories that exist only in test have no number, so they become NaN.
#    Fill them with -1 (or the median) before scaling.
X_train[categorical_f] = X_train[categorical_f].fillna(-1)
X_test[categorical_f]  = X_test[categorical_f].fillna(-1)

In [93]:
print(X_train.select_dtypes(exclude='number').columns)   # should be empty

Index([], dtype='object')

**Feature Scaling**

In [94]:
from sklearn.preprocessing import MinMaxScaler


scaler = MinMaxScaler()

# fit on train only, then transform both
X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),      # transform only, never fit on test
    columns=X_test.columns,
    index=X_test.index
)

In [ ]:
id_cols = ['Order', 'PID']   # change to your Id column names

# 1. Put the IDs back in front of the scaled features
train_final = pd.concat([df.loc[X_train_scaled.index, id_cols], X_train_scaled], axis=1)
test_final  = pd.concat([df.loc[X_test_scaled.index,  id_cols], X_test_scaled],  axis=1)

# 2. Add the target columns
train_final['SalePrice']     = y_train        # real price
test_final['SalePrice']      = y_test
train_final['SalePrice_log'] = y_train_log    # log price (what the model trains on)
test_final['SalePrice_log']  = y_test_log

train_final.head()

In [ ]:
train_final.to_csv('train_transformed.csv', index=False)
test_final.to_csv('test_transformed.csv', index=False)



```
one single file
```

In [ ]:
train_final['Set'] = 'train'
test_final['Set']  = 'test'

all_final = pd.concat([train_final, test_final])
all_final.to_csv('all_transformed.csv', index=False)